name: Conditionals Workflow

on: [push, pull_request]

jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - name: Only on main branch
              if: github.ref == 'refs/heads/main'
              run: echo "Running on main"

            - name: Fails on purpose
              continue-on-error: true
              run: exit 1

            - name: Runs if previous failed
              if: failure()
              run: echo "Previous step failed"

    push-only:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Only on push
              run: echo "This runs only on push events"
