name: Day 44 - Caching Demo

on: push

jobs:
    install-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: pip-cache

            - run: pip install requests
# testing cache hit
