name: Day 44 - Secrets as Env Variables

on:
    push:
        branches: [main]

jobs:
    use-secret-env:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v4

            - name: Use secret as environment variable
              env:
                  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
              run: |
                  echo "Docker username length check: ${#DOCKER_USER} characters"
                  echo "Using docker user in a command (safe way):"
                  echo "Logging in as user: $DOCKER_USER"

                  # re-run trigger
