name: Day 44 - Secrets Demo

on:
    push:
        branches: [main]

jobs:
    check-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v4

            - name: Print safe message
              run: echo "The secret is set:true"

            - name: Try printing secret directly
              run: echo "Direct value:${{ secrets.MY_SECRET_MESSAGE }}"
