name: Greet Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use custom greet action
        uses: ./.github/actions/setup-and-greet
        with:
          name: "Amit"
          language: "mr"
