name: Hello Workflow

on: push

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: print greeting
              run: echo "Hello from github action"
                        

