name: Hosted Runners Demo

on: push

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print details
        run: |
          echo "OS: Ubuntu Latest"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Print details
        run: |
          echo "OS: Windows Latest"
          echo "Hostname: $env:COMPUTERNAME"
          echo "User: $env:USERNAME"

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Print details
        run: |
          echo "OS: macOS Latest"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
          