name: PR Check

on:
  pull_request:
    branches: [main]

jobs:
  pr-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print branch info
        run: | 
          echo "PR check running for branch: ${{ github.head_ref }}"