name: Smart Pipeline

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Linting code"

    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running tests"

    summary:
        needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
            - if: github.ref == 'refs/heads/main'
              run: echo "Main branch push"

            - if: github.ref != 'refs/heads/main'
              run: echo "Feature branch push"

            - run: echo "Commit - ${{ github.event.commits[0].message }}"
