name: Run Tests

on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Run fake tests
              run: |
                  echo "Running tests..."
                  echo "Simulating a test failure!"
                  exit 1
